Updated deep loss CNV calls
AlexsLemonade/OpenPBTA-analysis pull request #1101
Opened 2021-06-21 12:54 UTC by kgaonkar6

### Purpose/implementation Section

#### What scientific question is your analysis addressing?
Add logic for a "deep loss" call for focal CN output files.

#### What was your approach?
Changed:
https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/6bf301eea42a7f8812c3b14cee35a961097f8ecf/analyses/focal-cn-file-preparation/04-prepare-cn-file.R#L240-L247

To:
```

# Merge and annotated no X&Y
autosome_annotated_cn <- process_annotate_overlaps(cnv_df = cnv_no_xy,
                                                   txdb_exons = tx_exons) %>%
  # mark possible amplifications and deep loss in autosomes
  dplyr::mutate(status = dplyr::case_when(
    copy_number > (2 * ploidy) ~ "amplification",
    copy_number <= ploidy-2 ~ "deep loss",
    TRUE ~ status
  ))

```
Changed:
https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/6bf301eea42a7f8812c3b14cee35a961097f8ecf/analyses/focal-cn-file-preparation/04-prepare-cn-file.R#L265-L267

To:
```
  sex_chrom_annotated_cn <- process_annotate_overlaps(cnv_df = cnv_sex_chrom,
                                                      txdb_exons = tx_exons) %>%
  # mark possible deep loss in sex chromosome
  dplyr::mutate(status = case_when(
    copy_number == 0  ~ "deep loss",
   TRUE ~ status
  ))
```

#### What GitHub issue does your pull request address?
#1099

### Directions for reviewers. Tell potential reviewers what kind of feedback you are soliciting.

#### Which areas should receive a particularly close look?
Please verify in the conditions for "deep loss" seem right to you.

#### Is there anything that you want to discuss further?
NA

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes

### Results

#### What types of results are included (e.g., table, figure)?
table

#### What is your summary of the results?
"Deep loss" calls were added to focal CN files for autosomes and X+Y calls.

#### Reproducibility Checklist

- [ ] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [ ] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [ ] The analytical code is documented and contains comments.

2021-06-22 13:19 UTC, kgaonkar6 commented
@jharenza 
I’ve now updated the CN==0 as the only criteria for “deep loss” 

>The chromosome arm and cytoband level copy_number annotation uses only "gain" and "loss" as status; amplification is converted to gain
Should we convert the "deep loss" added in this PR as "loss" for cytoband annotation OR do we want to add amplification and deep loss annotation to cytobands?
Does this sound ok as is  ? 

XY chromosomes don’t have a logic in the current code y to add applications does that sound ok too?

2021-06-22 19:39 UTC, jharenza approved these changes
This looks good, just want to switch the nomenclature to `deep deletion`

2021-06-22 19:39 UTC, jharenza commented on analyses/focal-cn-file-preparation/04-prepare-cn-file.R
> +    copy_number == 0 ~ "deep loss",
```suggestion
    copy_number == 0 ~ "deep deletion",
```

just so we don't have to change it later, updating to this standard nomenclature

2021-06-22 19:39 UTC, jharenza commented on analyses/focal-cn-file-preparation/04-prepare-cn-file.R
> +    copy_number == 0  ~ "deep loss",
```suggestion
    copy_number == 0  ~ "deep deletion",
```

2021-06-22 19:39 UTC, jharenza commented on analyses/focal-cn-file-preparation/README.md
> +  Any segment that is copy neutral is filtered out of this table. In addition, [any segments with copy number <= (ploidy -2 ) in autosomes chromosomes](https://github.com/kgaonkar6/OpenPBTA-analysis/
```suggestion
  Any segment that is copy neutral is filtered out of this table. In addition, [any segments with copy number <= (ploidy -2 ) in autosomes chromosomes](https://github.com/kgaonkar6/OpenPBTA-analysis/blob/5e9b68ed0c37d6c87bc67ee1f95be9e47ec9b4ca/analyses/focal-cn-file-preparation/04-prepare-cn-file.R#L244-L247) and [copy_number==0 in X/Y chromosomes are marked as deep deletions](https://github.com/kgaonkar6/OpenPBTA-analysis/blob/5e9b68ed0c37d6c87bc67ee1f95be9e47ec9b4ca/analyses/focal-cn-file-preparation/04-prepare-cn-file.R#L270-L272) in the `status` column.
```

2021-06-22 20:06 UTC, kgaonkar6 commented
Thanks for the review @jharenza 🙌

2021-07-01 21:02 UTC, jharenza commented
> The chromosome arm and cytoband level copy_number annotation uses only "gain" and "loss" as status; amplification is converted to gain

For this, we should remove the following lines to retain amplifications:

https://github.com/kgaonkar6/OpenPBTA-analysis/blob/aee3127e537ae8fde80aba5a754774c9c3803343/analyses/focal-cn-file-preparation/05-define-most-focal-cn-units.Rmd#L92-L94

2021-07-01 21:03 UTC, jharenza requested changes
see comment about removing the amp-->gain change in XY seg file

2021-07-01 21:15 UTC, jharenza approved these changes

2021-07-01 21:58 UTC, jaclyn-taroni commented on analyses/focal-cn-file-preparation/README.md
> +  Any segment that is copy neutral is filtered out of this table. In addition, [any segments with copy number <= (ploidy -2 ) in autosomes chromosomes](https://github.com/kgaonkar6/OpenPBTA-analysis/
Based on my read of `analyses/focal-cn-file-preparation/04-prepare-cn-file.R`, this should be:

```suggestion
  Any segment that is copy neutral is filtered out of this table. In addition, [any segments with copy number > (2 * ploidy) are marked as amplifications](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/e2058dd43d9b1dd41b609e0c3429c72f79ff3be6/analyses/focal-cn-file-preparation/03-prepare-cn-file.R#L275) in the `status` column. 
Any segments with copy number == 0  are marked as deep deletions in the `status` column.
```

2021-07-02 01:25 UTC, jharenza approved these changes

2021-07-02 13:01 UTC, merged