Download data v20
AlexsLemonade/OpenPBTA-analysis pull request #1118
Opened 2021-07-26 18:09 UTC by kgaonkar6

### Purpose/implementation Section
v20 data release
- Changes:
 - Update copy_number_consensus_call with manta calls with FILTER==PASS
    - pbta-cnv-consensus.seg.gz
 - Update focal-cn-file-preparation with deep deletion status and with updated pbta-cnv-consensus.seg.gz above
    - consensus_seg_annotated_cn_autosomes.tsv.gz
    - consensus_seg_annotated_cn_x_and_y.tsv.gz
 - Add cnv and indel hostspots from MSKCC and TERT promoters  
    - pbta-snv-scavenged-hotspots.maf.tsv.gz
 - Update histology information 
   - latest pathology diagnosis for 7316-2686 
   - BS_0TCRV9AC as sample_type == Normal

### Data Release Checklist
- [ ] Is the table in doc/data-file-descriptions.md up to date?
- [ ] Is doc/data-format.md up to date?
- [ ] Is doc/release-notes.md up to date?
- [ ] Is download-data.sh up to date?
- [ ] Was download-data.sh tested and did it complete without error?
-->

2021-07-26 20:07 UTC, jharenza requested changes
Hi @kgaonkar6! The download worked perfectly to me, but I am going to request that you add the corresponding tickets to each update noted in the `release-notes.md`

2021-07-26 20:30 UTC, jharenza commented
Will you also add `s3://kf-openaccess-us-east-1-prd-pbta/data/release-v20-20210726/pbta-mb-pathology-subtypes.tsv` to the md5sum per #746

2021-07-30 21:29 UTC, jharenza approved these changes
LGTM now!

2021-08-05 00:53 UTC, kgaonkar6 commented
Please check download_script.sh again.
`release_notes.md` to be udpated once PR #1114 #1115 #1116 #1117 are merged

2021-08-05 19:31 UTC, jharenza requested changes
few update requests on the release notes

2021-08-05 19:31 UTC, jharenza commented on doc/release-notes.md
> +    - pbta-cnv-consensus.seg.gz
```suggestion
 - Update copy_number_consensus_call with manta calls with FILTER==PASS [#1113](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/1113)
 - Update reciprocal overlap rules for consensus CNV [#1125](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/1125)
    - pbta-cnv-consensus.seg.gz
    - pbta-cnv-consensus-gistic.zip
```

2021-08-05 19:31 UTC, jharenza commented on doc/release-notes.md
> +   - BS_0TCRV9AC as sample_type == Normal
```suggestion
 - Update histology information 
   - latest pathology diagnosis for 7316-2686 [#1032](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/1032)
   - BS_0TCRV9AC as sample_type == Normal
   - Add `cancer_group` for plot labeling per [#917](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/917)
```

2021-08-06 04:00 UTC, kgaonkar6 commented
Thanks for the review @jharenza !

2021-08-12 19:56 UTC, jaclyn-taroni commented
Re-requested @jharenza to make sure all requested changes are satisfied

2021-08-12 21:18 UTC, jharenza approved these changes
This looks good to me! Thanks!

2021-08-12 21:45 UTC, merged