Tp53 cnv domain loss
AlexsLemonade/OpenPBTA-analysis pull request #841
Opened 2020-11-13 16:09 UTC by kgaonkar6

### Purpose/implementation Section

#### What scientific question is your analysis addressing?
Find cnv losses that overlap domains in TP53  
 

- TAD = trans-activating domain (essential for function)
-  DBD = DNA-binding domain (residues 102–292)
-  TD = tetramerization domain (residues 326–356)

We want to subset CNV calls where the domain are lost which will possibly lead to loss of function to use for evaluation of TP53  inactivation score at a later step.

#### What was your approach?
I read in `consensus_seg_with_status.tsv` which we generate as a scratch file while running `02-add-ploidy-consensus.Rmd` in focal-cn-file-preparation which adds ploidy information to the consensus SEG file and adds a status column that defines gain and loss broadly. I

```
 Rscript -e "rmarkdown::render('analyses/focal-cn-file-preparation/02-add-ploidy-consensus.Rmd', clean = TRUE)"
```

We needed the start and end location of CNVs which I didn't find in `consensus_seg_annotated_cn_autosomes.tsv.gz` so from discussion with @jharenza we decided to use  the seg file. This file `consensus_seg_with_status.tsv` provided the location,ploidy and status so I'm using this file here.

#### What GitHub issue does your pull request address?

#837 

### Directions for reviewers. Tell potential reviewers what kind of feedback you are soliciting.

#### Which areas should receive a particularly close look?
I'm running a direct overlap for domain and CNVs locations.  Should CNVs be filtered for length? 

![image](https://user-images.githubusercontent.com/34580719/99092562-4ace6480-259f-11eb-8410-ed000b8268cd.png)

Loss are distributed as , for next steps we would need to check for double mutation so are 1 copy loss ok to keep for next steps or should we only look for more than 1 copy loss :
![image](https://user-images.githubusercontent.com/34580719/99092873-bdd7db00-259f-11eb-8778-230751958cee.png)

#### Is there anything that you want to discuss further?
I'm trying to make a staggered PR for #837 
1 ) #839 
2) This PR with TP53 cnv domain overlap

I specifically wanted to know does this work with renaming 03-evaluate-classifier.py to 04-evaluate-classifier.py ?

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes table

### Results

#### What types of results are included (e.g., table, figure)?
tp53-subset/loss_overlap_domains_tp53.tsv

#### What is your summary of the results?
276 unique bs_id have losses that overlap functionally relevant domains in TP53 .

#### Reproducibility Checklist

- [ ] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [ ] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [ ] The analytical code is documented and contains comments.

2020-11-13 20:46 UTC, jharenza requested changes
@kgaonkar6 thanks for this!

I am going to request you create a notebook for this, since there will be a lot of scientific discussion around this exploration and it will be useful to have it organized.

To address your questions:
>I'm running a direct overlap for domain and CNVs locations. Should CNVs be filtered for length?

I don't think we need to filter for CNV length. However, in looking at your `loss_overlap_domains_tp53.tsv` file, it does appear that all samples that have loss of any domain have loss of all domains. Perhaps you can print the full table in the notebook (combining pfam_id and NAME since these are redundant), but summarize the output more simply for use in the later steps. I would suggest combining the data into one row per BS_ID with columns: `TP53_status`, `TP53_CN`, `ploidy`.

>Loss are distributed as , for next steps we would need to check for double mutation so are 1 copy loss ok to keep for next steps or should we only look for more than 1 copy loss :

I think we might need to state this differently. The way I am thinking about this is more: how many copies (alleles) are being retained, knowing that both alleles are required for function. Based on this, I suggest we create a subset of TP53 loss as our "high-confidence" calls, which would be CN <= 1. This looks to be 56 patients. 

Then, will you plot TP53 scores (violin with jitter?) by samples with copy numbers of 0, 1, 2, 3? Of course, this is not the only alteration (we have SNV and LFS to consider), but perhaps we can be assured that those with 0 or 1 copy tend to have higher scores?

I would remove the `tp53-subset` folder and put all of your output tables into `results`.

2020-11-17 16:44 UTC, kgaonkar6 commented
@jharenza I incorporated the changes you requested above and also resolved the conflict with master.

2020-11-18 21:32 UTC, jharenza approved these changes
@kgaonkar6 this looks great and the "high-confidence" CNVs of 0 or 1 copy TP53 check out!

I just ask that you add some comments under the last header of your notebook re: the plots.

"Do samples with copy numbers of 0 and 1 copy of TP53 tend to have higher scores? Yes"

2020-11-19 01:50 UTC, jharenza commented on analyses/tp53_nf1_score/README.md
> +`03-tp53-cnv-loss-domain.Rmd` here copy_number of consensus CNV reginos overlapping TP53 were compared to TP53 classifier score. We find TP53<=1 is supported by higher TP53 classifier score so we onl
```suggestion
`03-tp53-cnv-loss-domain.Rmd` here copy_number of regions overlapping TP53 functional domains were compared to TP53 classifier score. We find tumors with TP53 copies <=1 have higher TP53 classifier scores, so we only retain biospecimens with <= 1 copy TP53 as high confidence TP53 loss. 
```

2020-11-19 01:52 UTC, jharenza commented on analyses/tp53_nf1_score/README.md
> +`02-qc-rna_expression_score.Rmd` here expression of TP53 gene was compared to TP53 classifier score but we didn't find any correlation between TP53 expression is supported by tp53 inactivation score.
```suggestion
`02-qc-rna_expression_score.Rmd` here expression of TP53 gene was compared to TP53 classifier score. We didn't find a strong correlation between TP53 expression and TP53 inactivation score, thus, expression and classifier score together cannot predict function.
```

2020-11-19 01:52 UTC, jharenza approved these changes

2020-11-19 03:11 UTC, merged