Hgg tp53 status
AlexsLemonade/OpenPBTA-analysis pull request #943
Opened 2021-02-16 00:26 UTC by kgaonkar6

⚠️ merge after #942 is in master

### Purpose/implementation Section

#### What scientific question is your analysis addressing?
Adding TP53 status along with evidence columns(tp53_XYZ from classifier,SNV and CNV calls to HGG samples.

#### What was your approach?
I am using tp53_nf1_score/results/tp53_altered_status.tsv to add the tp53_altered status to the subtypes already annotated to the sample_id

#### What GitHub issue does your pull request address?
#807 

### Directions for reviewers. Tell potential reviewers what kind of feedback you are soliciting.

#### Which areas should receive a particularly close look?

#### Is there anything that you want to discuss further?

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?

### Results

#### What types of results are included (e.g., table, figure)?

#### What is your summary of the results?

#### Reproducibility Checklist

- [ ] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [ ] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [ ] The analytical code is documented and contains comments.

2021-02-17 21:28 UTC, jharenza requested changes
I think that we want to capture any TP53-altered samples in the subtyping, rather than just loss. For `HGG_molecular_subtype.tsv`, will you also add `TP53 activated`?

2021-02-17 21:28 UTC, jharenza commented on analyses/molecular-subtyping-HGG/10-HGG-TP53-annotation.Rmd
> +In this notebook we will annotate HGG samples with TP53 status we obtained from snv/cnv and tp53 loss classifier. We belive TP53 annotation will add useful information to the current known subtypes a
```suggestion
In this notebook we will annotate HGG samples with TP53 status we obtained from snv/cnv and TP53 classifier. We believe TP53 annotation will add useful information to the current known subtypes as we see TP53 mutations co-occurring with H3 mutations.
```

2021-02-18 15:25 UTC, kgaonkar6 commented
> I think that we want to capture any TP53-altered samples in the subtyping, rather than just loss. For `HGG_molecular_subtype.tsv`, will you also add `TP53 activated`?
will do!

2021-02-18 18:36 UTC, jharenza approved these changes
looks great, thank you!

2021-02-18 18:45 UTC, merged